development:
  dialect: postgres
  datasource: host=localhost port=5432 user=postgres password=092235 dbname=golang sslmode=disable
  dir: migrations
  table: migrations # save history -> create migrations table in postgres